#!/usr/bin/env python3
# luxarch:fleet-start-after-compact hook v1 - DO NOT edit this file - it is emitted by `luxarch --emit hooks`; re-emit to update.
"""After any compaction, tell the agent to run `/fleet-start` before anything else.

Claude Code compacts on its own (when the context fills, and while a session sits idle), so "the
owner runs /compact, then /fleet-start" no longer describes every compact. The CLAUDE.md line asking
for `/fleet-start` after a compact only works if someone remembers it; this hook fires on the event.

SessionStart(compact): its stdout lands in the post-compaction context. A hook cannot invoke a skill,
so this is an instruction the agent reads, not a call. Nothing here can run BEFORE a compact (PreCompact
can only allow or block it), which is why decisions are persisted to LuxPM as they are made.
Never blocks, never errors out.
"""

from __future__ import annotations

import contextlib
import sys

_TEXT = (
    "This session was just compacted. Before anything else, run `/fleet-start`: re-read this "
    "repo's CLAUDE.md and the conduct standard's sections it names, and rehydrate from LuxPM. "
    "The summary above is not the state; LuxPM and the repo are."
)


def main() -> int:
    # A reminder must never break a session: a closed stdout is not an error worth surfacing.
    with contextlib.suppress(OSError):
        sys.stdout.write(_TEXT + "\n")
    return 0


sys.exit(main())
