{
 "title": "Kasa Collector  - Energy (By Measurement)",
 "description": "Kasa Collector provides a way of collecting real-time energy data from  Kasa Smart Plugs. These Grafana dashboards offer visualizations for their Current, Voltage, Power, and Total Watt Hours.",
 "tags": [
  "influxdb",
  "kasa-collector"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "device_alias",
    "label": "Device",
    "query": "SHOW TAG VALUES WITH KEY = \"device_alias\""
   },
   {
    "name": "plug_alias",
    "label": "Plug",
    "query": "SHOW TAG VALUES WITH KEY = \"plug_alias\" WHERE \"device_alias\" =~ /^$device_alias$/"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,15s,30s,1m,5m,10m,15m,1h,3h,6h,12h,1d,3d,1w"
   }
  ]
 },
 "panels": [
  {
   "title": "Power (Combined)",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"v\") FROM (SELECT last(\"power_mw\") AS v FROM \"emeter\" WHERE \"equipment_type\" = 'device' AND (\"device_alias\" =~ /^$device_alias$/) AND $timeFilter GROUP BY \"device_alias\")"
    }
   ]
  },
  {
   "title": "Watt-Hours (Combined)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"v\") FROM (SELECT (last(\"total_wh\") - first(\"total_wh\")) AS v FROM \"emeter\" WHERE \"equipment_type\" = 'device' AND (\"device_alias\" =~ /^$device_alias$/) AND $timeFilter GROUP BY \"device_alias\")"
    }
   ]
  },
  {
   "title": "Current (Combined)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"v\") FROM (SELECT last(\"current_ma\") AS v FROM \"emeter\" WHERE \"equipment_type\" = 'device' AND (\"device_alias\" =~ /^$device_alias$/) AND $timeFilter GROUP BY \"device_alias\")"
    }
   ]
  },
  {
   "title": "Voltage (Mean)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"v\") FROM (SELECT last(\"voltage_mv\") AS v FROM \"emeter\" WHERE \"equipment_type\" = 'device' AND \"voltage_mv\" > 100000 AND (\"device_alias\" =~ /^$device_alias$/) AND $timeFilter GROUP BY \"device_alias\")"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "alias": "$tag_device_alias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "select": [
      [
       { "params": [ "power_mw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_alias", "operator": "=~", "value": "/^$device_alias$/" }
     ]
    }
   ]
  },
  {
   "title": "Watt-Hours",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_device_alias",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "device_alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "select": [
      [
       { "params": [ "total_wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "device_alias", "operator": "=~", "value": "/^$device_alias$/" }
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "alias": "$tag_device_alias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_alias" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kasa_energy",
     "query": "SELECT mean(\"current_ma\") FROM \"emeter\" WHERE (\"device_alias\" =~ /^$device_alias$/) AND \"current_ma\" > 1 AND $timeFilter GROUP BY time($__interval), \"device_alias\" fill(null)",
     "select": [
      [
       { "params": [ "current_ma" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_alias", "operator": "=~", "value": "/^$device_alias$/" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_device_alias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kasa_energy",
     "query": "SELECT mean(\"voltage_mv\") FROM \"emeter\" WHERE (\"device_alias\" =~ /^$device_alias$/) AND \"voltage_mv\" > 100000 AND $timeFilter GROUP BY time($__interval), \"device_alias\" fill(null)",
     "select": [
      [
       { "params": [ "voltage_mv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_alias", "operator": "=~", "value": "/^$device_alias$/" }
     ]
    }
   ]
  },
  {
   "title": "Plugs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "alias": "$tag_plug_alias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "plug_alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "select": [
      [
       { "params": [ "power_mw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "plug_alias", "operator": "=~", "value": "/^$plug_alias$/" }
     ]
    }
   ]
  },
  {
   "title": "Watt-Hours",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_plug_alias",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "plug_alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "select": [
      [
       { "params": [ "total_wh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "plug_alias", "operator": "=~", "value": "/^$plug_alias$/" }
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "alias": "$tag_plug_alias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "plug_alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "emeter",
     "select": [
      [
       { "params": [ "current_ma" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "plug_alias", "operator": "=~", "value": "/^$plug_alias$/" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "alias": "$tag_plug_alias",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "plug_alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kasa_energy",
     "query": "SELECT mean(\"voltage_mv\") FROM \"emeter\" WHERE (\"plug_alias\" =~ /^$plug_alias$/) AND \"voltage_mv\" > 100000 AND $timeFilter GROUP BY time($__interval), \"plug_alias\" fill(null)",
     "select": [
      [
       { "params": [ "voltage_mv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "plug_alias", "operator": "=~", "value": "/^$plug_alias$/" }
     ]
    }
   ]
  }
 ]
}